avasus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from rest_framework import routers

from users import views as user_views
from forum import views as forum_views

router = routers.DefaultRouter()
router.register(r'api/users', user_views.UserViewSet)
router.register(r'api/categories', forum_views.CategoryViewSet)
router.register(r'api/subforuns', forum_views.SubForumViewSet)
router.register(r'api/topics', forum_views.TopicViewSet)
router.register(r'api/topicresponses', forum_views.TopicResponseViewSet)


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path("accounts/", include("users.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("forum/", include("forum.urls")),
    # path('users/', views.UserViewSet.as_view({'get': 'retrieve'})),
    # path('groups/', views.GroupViewSet.as_view({'get': 'retrieve'}))
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + router.urls

forum/urls.py
# forum/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('subforum/', SubForumFormCreateView.as_view(), name="subforum-create-form"),
    path('subforum/<int:pk>', SubForumInfoView.as_view(), name="subforum-info"),
    path('subforum/<int:subforum>/new_topic', TopicFormCreateView.as_view(), name="topic-create-form"),
    path('subforum/<int:pk>/edit', SubForumFormEditView.as_view(), name="subforum-edit-form"),
    path('topic/<int:pk>', TopicInfoView.as_view(), name="topic-info"),
    path('topic/<int:topic>/new_response', TopicResponseFormCreateView.as_view(), name="response-create-form"),
    path('topic/<int:pk>/close', close_topic, name="topic-close"),
    path('topic/<int:pk>/open', open_topic, name="topic-open"),
    path('topic/<int:pk>/remove/<int:response>', remove_response, name="remove-response"),
]

forum/models.py
from django.db import models

from users.models import CustomUser

import markdown

# Create your models here.

class Category(models.Model):
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
    name = models.CharField('Nome', max_length=120, help_text='Informe o nome da categoria')
    is_active = models.BooleanField('Ativo', default=True, help_text='Indica se a categoria está ativa')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)

    def __str__(self) -> str:
        return self.name

class SubForum(models.Model):
    class Meta:
        verbose_name = 'SubForum'
        verbose_name_plural = 'SubForums'
    title = models.CharField('Título', max_length=120, help_text='Informe o título do subfórum')
    description = models.TextField('Descrição', help_text='Informe a descrição do subfórum')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Categoria")

    creator = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE,
        related_name='created_subforuns', verbose_name="Categoria"
    )
    students = models.ManyToManyField(CustomUser, verbose_name="Alunos")

    is_active = models.BooleanField('Ativo', default=True, help_text='Indica se o subfórum está ativo')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self) -> str:
        return self.title
    
    @property
    def sorted_topics(self):
        return self.topic_set.order_by('-created_at')
    
    @property
    def qtd_posts(self):
        qtd = 0
        for topic in self.topic_set.all():
            qtd += topic.topicresponse_set.all().count()
        return qtd

class Topic(models.Model):
    class Meta:
        verbose_name = 'Tópico'
        verbose_name_plural = 'Tópicos'
    title = models.CharField('Título', max_length=120, help_text='Informe o título do tópico')
    content = models.TextField('Conteúdo', help_text='Informe o conteúdo do tópico')
    subforum = models.ForeignKey(SubForum, on_delete=models.CASCADE, verbose_name="SubForum")

    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Autor")
    is_closed = models.BooleanField('Trancado', default=False, help_text='Indica se o tópico está trancado')

    is_active = models.BooleanField('Ativo', default=True, help_text='Indica se o tópico está ativo')
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    
    def __str__(self) -> str:
        return "[Trancado] " + self.title if self.is_closed else self.title

    @property
    def sorted_responses(self):
        return self.topicresponse_set.filter(is_active=True).order_by('created_at')
    
    @property
    def qtd_responses(self):
        return self.topicresponse_set.all().count()
    
    @property
    def datetime_last_response(self):
        resps = self.topicresponse_set.order_by('created_at').all() 
        if (len(resps) > 0):
            return resps[0].created_at
        return self.updated_at
    
    @property
    def md_content(self):
        return markdown.markdown(self.content)

class TopicResponse(models.Model):
    class Meta:
        verbose_name = 'Resposta'
        verbose_name_plural = 'Respostas'
    content = models.TextField('Resposta', help_text='Informe a resposta ao tópico')
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name="Tópico")

    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Autor")
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    is_active = models.BooleanField('Ativo', default=True, help_text='Indica se a resposta está ativa')
    def __str__(self) -> str:
        return self.content_preview
    
    @property
    def md_content(self):
        return markdown.markdown(self.content)
    
    @property
    def content_preview(self):
        if len(self.content) > 20:
            return self.content[0:20]
        return self.content
    
    content_preview.fget.short_description = "Conteúdo"

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Avasus{% endblock %}</title>
</head>
<body>
  <main>
    <div style="margin:auto;text-align:center;">
      <h1>
        <img src="https://avasus.ufrn.br/theme/image.php/avasus2/theme/1666351836/logo" alt="AVASUS">   
      </h1>
      <p >
        Promovendo conhecimento integrado e acessível em educação para a saúde.
      </p>
    </div>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1 style="margin:auto;text-align:center;">Bem vindo ao AVASUS!</h1>
{% if user.is_authenticated %}
    <div style="margin:auto;text-align:center;">
        <p>
        {% if user.is_professor %}
            Olá Professor {{ user.name }}!
        {% else %}
            Olá aluno {{ user.name }}!
        {% endif %}
        <strong>CPF: </strong> {{ user.cpf }}
        <strong>Idade: </strong>{{ user.age }} anos
        <strong>Data de nascimento: </strong>{{ user.birth_date }}
        </p>
        <button type="button">
            <a href="{% url 'logout' %}">Log Out</a>
        </button>
        {% if user.is_professor %}
        <button type="button">
            <a href="{% url 'subforum-create-form' %}">Criar novo subfórum</a>
        </button>
        {% endif %}

    </div>
    <div style="margin:auto;text-align:center;">
        <h3>Subfóruns associados:</h3>
        {% if user.is_professor %}
            <table style="margin:auto;text-align:left;">
                <tr>
                    <th>Titúlo</th>
                    <th>Descrição</th>
                    <th>Professor Responsável</th>
                    <th>Criado em</th>
                </tr>
                {% for field in user.created_subforuns.all %}
                <tr>
                    <td><a href="/forum/subforum/{{ field.id }}">{{ field.title }}</a></td>
                    <td>{{ field.description }}</td>
                    <td>{{ field.creator }}</td>
                    <td>{{ field.created_at }}</td>
                </tr>
                {% endfor %}
            </table>
        {% else %}
            <table>
                <tr>
                    <th>Titúlo</th>
                    <th>Descrição</th>
                    <th>Professor Responsável</th>
                    <th>Criado em</th>
                </tr>
                {% for field in user.subforum_set.all %}
                <tr>
                    <td><a href="{% url 'subforum-info' field.id %}">{{ field.title }}</a></td>
                    <td>{{ field.description }}</td>
                    <td>{{ field.creator }}</td>
                    <td>{{ field.created_at }}</td>
                </tr>
                {% endfor %}
            </table>
            <br />
            {% if user.subforum_set.all.count == 0 %}
                Parece que você não foi incluído em nenhum fórum ainda.
                <br />
                Solicite ao seu professor que te inclua.
                <br />
            {% endif %}
        {% endif %}
        <button type="button">
            <a href="{% url 'logout' %}">Log Out</a>
        </button>
        {% if user.is_professor %}
        <button type="button">
            <a href="{% url 'subforum-create-form' %}">Criar novo subfórum</a>
        </button>
        {% endif %}
    </div>
{% else %}
    <div style="margin:auto;text-align:center;">
        <p>Você não está logado</p>
        <button type="button">
            <a href="{% url 'login' %}">Entrar</a>
        </button>
        <button type="button">
            <a href="{% url 'signup-student' %}">Cadastre-se</a>
        </button>
    </div>
{% endif %}
{% endblock %}

templates/user-detail.html
{% extends 'base.html' %}

{% block title %}{{ object }}{% endblock %}

{% block content %}
<div style="text-align: center;">
{% if object.is_professor %}
    <h2>Professor {{ object.call_name }}</h2>
{% else %}
    <h2>Aluno {{ object.call_name }}</h2>
{% endif %}
<p>
    <strong>Nome:</strong> {{ object.name }}
    <strong>Nome Social:</strong> {{ object.social_name }}
    <strong>Idade:</strong> {{ object.age }}
</p>
<p><strong>Usuário desde:</strong> {{ object.created_at }}</p>
<p><strong>Quantidade de subfóruns que participa:</strong> {{ object.qtd_subforums }}</p>
<p><strong>Quantidade de tópicos criados:</strong> {{ object.topic_set.all.count }}</p>
<p><strong>Quantidade de respostas dadas:</strong> {{ object.topicresponse_set.all.count }}</p>
<button type="button">
    <a href="{% url 'home' %}">Voltar para a tela inicial</a>
  </button> 
</div>

{% endblock %}